EVENT_SCHEDULE_COLUMNS = {
    "RoundNumber": "round_number",
    "Country": "country",
    "Location": "location",
    "OfficialEventName": "official_event_name",
    "EventDate": "event_date",
    "EventName": "event_name",
    "EventFormat": "event_format",
    "Session1": "session_1",
    "Session1DateUtc": "session_1_date_utc",
    "Session2": "session_2",
    "Session2DateUtc": "session_2_date_utc",
    "Session3": "session_3",
    "Session3DateUtc": "session_3_date_utc",
    "Session4": "session_4",
    "Session4DateUtc": "session_4_date_utc",
    "Session5": "session_5",
    "Session5DateUtc": "session_5_date_utc",
    "F1ApiSupport": "f1_api_support",
}

RACE_RESULTS_COLUMNS = {
    "Season": "season",
    "RoundNumber": "round_number",
    "EventName": "event_name",
    "DriverNumber": "driver_number",
    "DriverId": "driver_id",
    "Abbreviation": "driver_abbreviation",
    "FullName": "driver_name",
    "TeamId": "team_id",
    "TeamName": "team_name",
    "CountryCode": "country_code",
    "GridPosition": "grid_position",
    "Position": "finish_position",
    "ClassifiedPosition": "classified_position",
    "Time": "race_time",
    "Status": "status",
    "Points": "points",
    "Laps": "laps",
}